### ISSUE TITLE
Replica.Minimal doesn't exist anymore ?

### ISSUE THREAD

**Issue by teto** [ReplicaTest/REPLica#70]
I grepped ReplicaTest/replica-dhall for it but couldn't find it (and tests fail). 
The doc and examples in this repo still refer to it so I wonder if I am missing anything ?

**Comment by berewt** [comment]
I have to update the documentation indeed. It's simply `Replica.Test` now (or `Replica.Success` if you want to just check that the exit code is 0). I should also take time to produce a better set of examples for `replica-dhall`.
At the moment, as always (and unfortunately) the best source to grasg replica-dhall syntax is too look at the examples in [`test.dhall`](https://github.com/ReplicaTest/REPLica/blob/main/tests.dhall)

**Comment by teto** [comment]
ok thanks, that's how i did it but wanted to confirm first. I also was wondering if there was any reason as to why the dhall component is in another repo  https://github.com/ReplicaTest/replica-dhall ? I find it more difficult to work with in general.
Maybe once hte doc is fixed, there could be a release so that we can go back to a stable point.

**Comment by berewt** [comment]
I wanted to be able to separate the release of Replica from those of replica-dhall. It allows me to add content to replica-dhall and to release it without having to perform a new replica release.
If I had done it earlier, for example, one could still easily continue to use `Minimal` if they specify the url of this specific version of replica-dhall.

I should really start to use releases on replica-dhall though, so that we can easily specify the version of replica-dhall we want to work with.

**Comment by berewt** [comment]
Much of the dhall part in Readme is using the old syntax, I'm fixing it today.
